name: Build Qamera qmod

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: QPM Rust Action
        uses: Fernthedev/qpm-action@v1
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          resolve_ndk: true
          cache: true

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Build
        run: bash build.sh

      - name: Upload qmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: qamera-qmod
          path: qamera.qmod
